### PR TITLE
feat: fix minor issues in artifact page

### PR DESCRIPTION
**Pull request by VasuDevrani**
fixes issues #7, #15, #43, #47, #49, #38, #35, #46

This PR alongside #51 completes the [final](https://github.com/VasuDevrani/artifact-explorer-oras/milestone/2) milestone

### CODE REVIEW

**Comment by qweeah** [comment]
You need to do sth like below to fix all the issue
> fixes issues https://github.com/VasuDevrani/artifact-explorer-oras/issues/7,fixes  https://github.com/VasuDevrani/artifact-explorer-oras/issues/15, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/43, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/47, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/49, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/38, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/35, fixes https://github.com/VasuDevrani/artifact-explorer-oras/issues/46

**Comment by qweeah** [comment]
Let's merge this and I will manually check all the issues

**Comment by VasuDevrani** [comment]
> You need to do sth like below to fix all the issue
> 
> > fixes issues #7  #15, fixes #43, fixes #47, fixes #49, fixes #38, fixes #35, fixes #46

also fixes #48 #34 #31

**Comment by qweeah** [comment]
All closed except https://github.com/VasuDevrani/artifact-explorer-oras/issues/7

**Pull request merged**
